---
title: "Material de Apoio ao Ensino Médio  no Brasil"
subtitle: "(principalmente na rede pública)"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Como complementar os estudos no ensino médio?

* Pandemia e educação no Brasil
* Ensino remoto
* Base Nacional Comum Curricular - http://basenacionalcomum.mec.gov.br/


## Iniciativas pelo Brasil

* Secretaria da Educação da Bahia
    + Plataforma Anísio Teixeira - http://pat.educacao.ba.gov.br/
    + possui rotinas de estudos, sugestões de conteúdos e vídeos, .... excelente material  


* Currículo Paulista
    + materiais de anos anteriores e adaptados ao Novo Ensino Médio - https://efape.educacao.sp.gov.br/curriculopaulista/ensino-medio/materiais-de-apoio-2/


## No RS

* Novo Ensino Médio - http://portal.educacao.rs.gov.br/novo-ensino-medio
    + página com legislação, documentos e informações - para professores, educadores, gestores ...;
    + E para estudantes? Existe alguma plataforma com material de apoio?

### Como produzir em nosso Estado um material online, gratuito e de qualidade? *(Com o auxílio de Secretarias, escolas e professores, estudantes e pais, ...)*

* Do site da Secretaria de Educação - https://educacao.rs.gov.br/  
    + Plataforma Digital de Leitura - https://www.arvore.com.br/
    + Preparação para ENEM e vestibulares - https://www.resolvesim.com.br/   
    
    
* Do site do IFRS - Instituto Federal Rio Grande do Sul
    + Cursos online, gratuitos e abertos - https://moodle.ifrs.edu.br/course/index.php?categoryid=38   
    
    
* Como a Universidade também pode auxiliar nesse processo?
    
* Precisamos:
    + Rotina de estudos: planos para professores e alunos, tarefas, ... ;
    + Bibliografia: livros didáticos e de leitura, apostilas, ... (online e impresso);
    + Material de apoio: textos, áudios, vídeos/filmes, ... ;
    + Discussões e dúvidas: fóruns, chats, apresentações, ... *(monitorias?)*
    + *(Eventos virtuais?, congressos?, ...)*